version: '0.1'

services:

  api:
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  ui:
    build: ./ui
    volumes:
      - './ui:/app'
      - '/ui/node_modules'
    ports:
      - 8080:8080