version: '0.1'

services:

  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  # ui:
  #   build: ./ui
  #   volumes:
  #     - './ui:/app'
  #     - '/ui/node_modules'
  #   ports:
  #     - 8080:8080